name: Update Exoplanet Data

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from NASA API
      run: |
        curl "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,sy_dist,pl_orbper,pl_orbsmax,pl_rade,pl_masse,pl_eqt,st_teff+from+ps&format=json" -o exoplanet_data.json

    - name: Move data to assets/json directory
      run: |
        mv exoplanet_data.json assets/json/exoplanet_data.json

    - name: Setup SSH deploy key
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add assets/json/exoplanet_data.json
        git commit -m "Update exoplanet data" || exit 0
        git remote set-url origin git@github.com:Leyber91/project-leyber-212-website.git
        git push
